# Default joint-training configuration for MNIST image experiments.
seed: 1
device: cuda
target_dataset: mnist
dim: 784
image_shape: [1, 28, 28]
unet_model_channels: 64
unet_channel_mult: [1, 2, 4]
unet_num_res_blocks: 2
unet_attention_resolutions: [7]
unet_num_heads: 1
unet_num_head_channels: 8
unet_dropout: 0.0
hidden_size: 0
hidden_layers: 0
time_embedding: sinusoidal
concat_t_emb: true
lr: 0.0002
batch_size: 128
epochs: 200000
model_grad_clip: 1.0
ema: 0.99
ema_start_step: 0
use_minibatch_ot: true
baseline_latent: gaussian
quantile_checkpoint: null
freeze_quantile: false
eval_step: 10000
eval_sample: 10000
eval_batch: 10000
big_eval_samples: 0
big_eval_step: 0
num_steps_eval: 100
sampler: gauss
metric_batch_size: 4096
metric_blur: 0.05
latent_viz_samples: 512
latent_atlas_grid: 6
sample_vis_interval: 5000
sample_vis_count: 64
sample_vis_nrow: 8
fid_eval_interval: 10000
fid_num_gen: 10000
fid_image_size: 28
fid_batch_size: 256
fid_gen_batch: 512
name: null
mode: fm_and_quantile
q_ntrain: 20000
q_batch: 256
q_u_eps: 1.0e-8
q_lr: 2.0e-4
q_loss_weight: 5.0
quantile_const_iters: 20000
quantile_decay_iters: 5000
q_val_interval: 5000
q_val_samples: 1024
q_ema: 0.99
q_use_ema: true
q_ot_epsilon: 1.0
q_objective: plan_action
q_input_transform: bounded
lambda_reg: 0.1
metric: ot
q_rqs_bins: 16
q_rqs_bound: 3.0
q_rqs_layers: 1
runs_dir: null
log_wandb: true
wandb_entity: Appliedmathlab
wandb_group: null
wandb_project: Learn-Noise-Images
