# Default joint-training configuration for CIFAR-10 experiments.
seed: 1
device: cuda
target_dataset: cifar10
dim: 3072
image_shape: [3, 32, 32]
hidden_size: 0
hidden_layers: 0
time_embedding: sinusoidal
concat_t_emb: true
lr: 0.0002
batch_size: 128
epochs: 400000
model_grad_clip: 1.0
ema: 0.9999
ema_start_step: 0
warmup_lr: 5000
use_minibatch_ot: true
baseline_latent: gaussian
baseline_flow: linear
baseline_flow_T: 1.0
baseline_mmd_b: 1.0
baseline_kac_a: 9.0
baseline_kac_c: 3.0
baseline_kac_epsilon: 1.0e-6
baseline_kac_lookup_M: 5000
baseline_kac_lookup_K: 1024
quantile_checkpoint: null
freeze_quantile: false
eval_step: 10000
eval_sample: 10000
eval_batch: 10000
big_eval_samples: 0
big_eval_step: 0
num_steps_eval: 100
latent_viz_samples: 512
latent_atlas_grid: 6
sample_vis_interval: 10000
sample_vis_count: 64
sample_vis_nrow: 8
fid_eval_interval: 20000
fid_num_gen: 10000
fid_image_size: 32
fid_batch_size: 512
fid_gen_batch: 512
name: null
mode: fm_and_quantile
q_ntrain: 20000
q_batch: 128
q_u_eps: 1.0e-8
q_lr: 2.0e-4
q_loss_weight: 5.0
quantile_const_iters: 20000
quantile_decay_iters: 5000
q_val_interval: 5000
q_val_samples: 1024
q_ema: 0.99
q_use_ema: False
q_ot_epsilon: 1.0
q_objective: plan_action
lambda_reg: 4
metric: ot
q_rqs_bins: 16
q_rqs_bound: 5.0
q_rqs_layers: 3
runs_dir: null
log_wandb: true
wandb_entity: Appliedmathlab
wandb_group: null
wandb_project: Learn-Noise-Images
