# Default joint-training configuration for 2D experiments.
seed: 1
device: cuda
target_dataset: checker  # override via --override target_dataset=...
dim: 2
hidden_size: 64
hidden_layers: 3
time_embedding: sinusoidal
concat_t_emb: true
lr: 0.0002
batch_size: 128
epochs: 200000
model_grad_clip: 1.0
ema: 0.999
ema_start_step: 0
use_minibatch_ot: true
baseline_latent: gaussian
baseline_flow: linear
baseline_flow_T: 1.0
baseline_mmd_b: 1.0
baseline_kac_a: 9.0
baseline_kac_c: 3.0
baseline_kac_epsilon: 1.0e-6
baseline_kac_lookup_M: 5000
baseline_kac_lookup_K: 1024
quantile_checkpoint: null
freeze_quantile: false
eval_step: 10000
eval_sample: 20000
eval_batch: 20000
big_eval_samples: 100000
big_eval_step: 50000
num_steps_eval: 100
name: null
mode: fm_and_quantile
q_ntrain: 20000
q_batch: 256
q_u_eps: 1.0e-10
q_lr: 2.0e-4
q_loss_weight: 50.0
quantile_const_iters: 20000
quantile_decay_iters: 5000
q_val_interval: 5000
q_val_samples: 2048
q_ema: 0.99
q_use_ema: true
q_ot_epsilon: 1.0
q_objective: plan_action
lambda_reg: 0.0
metric: ot
q_rqs_bins: 16
q_rqs_bound: 5.0
q_rqs_layers: 3
image_shape: null
runs_dir: null
log_wandb: true
wandb_entity: Appliedmathlab
wandb_group: null
wandb_project: Learn-Noise-2D
