# Default joint-training configuration for the 2D Neal funnel experiment.
seed: 1
device: cuda
target_dataset: funnel
dim: 2
hidden_size: 64
hidden_layers: 3
time_embedding: sinusoidal
concat_t_emb: true
lr: 0.0002
batch_size: 128
epochs: 100000  #200000 for baselines
model_grad_clip: 1.0
ema: 0.999
ema_start_step: 0
use_minibatch_ot: false 
baseline_latent: gaussian
baseline_flow: linear
baseline_flow_T: 1.0
student_t_df:
  - 20.0
  - 4.0
student_t_scale:
  - 1.0
  - 1.0
quantile_checkpoint: null
freeze_quantile: true 
eval_step: 10000
eval_sample: 20000
eval_batch: 20000
big_eval_samples: 1000000
big_eval_step: 50000
num_steps_eval: 100
name: null
mode: fm_and_quantile
q_ntrain: 50000
q_batch: 128
q_u_eps: 1e-10
q_lr: 1.0e-4
q_loss_weight: 1.0
quantile_const_iters: 20000
quantile_decay_iters: 5000
q_val_interval: 50000
q_val_samples: 2048
q_ema: 0.999
q_use_ema: true
q_ot_epsilon: 1.0
q_objective: plan_action
lambda_reg: 0.0
metric: ot
q_input_transform: logit
q_rqs_bins: 32
q_rqs_bound: 500.0
q_rqs_layers: 1
image_shape: null
runs_dir: null
log_wandb: true
wandb_entity: Appliedmathlab
wandb_group: null
wandb_project: Learn-Noise-2D
